# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_homeui(object):
    def setupUi(self, homeui):
        homeui.setObjectName("homeui")
        homeui.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(17)
        homeui.setFont(font)
        self.centralwidget = QtWidgets.QWidget(homeui)
        self.centralwidget.setObjectName("centralwidget")
        self.PushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.PushButton_1.setGeometry(QtCore.QRect(590, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Tai Le")
        font.setPointSize(14)
        self.PushButton_1.setFont(font)
        self.PushButton_1.setObjectName("PushButton_1")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(660, 200, 20, 301))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(230, 140, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 391, 121, 141))
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_1.setGeometry(QtCore.QRect(230, 200, 431, 311))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.textEdit_1.setFont(font)
        self.textEdit_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_1.setObjectName("textEdit_1")
        homeui.setCentralWidget(self.centralwidget)

        self.retranslateUi(homeui)
        QtCore.QMetaObject.connectSlotsByName(homeui)

    def retranslateUi(self, homeui):
        _translate = QtCore.QCoreApplication.translate
        homeui.setWindowTitle(_translate("homeui", "Corpus"))
        self.PushButton_1.setText(_translate("homeui", "查询"))
